@server = http://localhost:8000
###
GET{{server}}
###
GET{{server}}/register
###
GET {{server}}/login
###
GET {{server}}/users
###회원가입 요청, 헤더 내용 아래쪽을 한줄 띄어야 인식한다.
POST {{server}}/register
Content-Type: application/json; charset=UTF-8

{
  "userid" : "orange",
  "pw" : "1234",
  "name" : "오렌지",
}

###로그인 요청
POST {{server}}/login
Content-Type: application/json; charset=UTF-8

{
  "userid" : "orange",
  "pw":"1234"
}